import { Document, Page, Text, View, StyleSheet, renderToBuffer } from "@react-pdf/renderer";
import type { GenerationTaskType, MatchedChunk } from "@/types/database";

const styles = StyleSheet.create({
  page: { padding: 40, fontSize: 11, fontFamily: "Helvetica", lineHeight: 1.5 },
  title: { fontSize: 18, fontFamily: "Helvetica-Bold", marginBottom: 4 },
  subtitle: { fontSize: 10, color: "#64748b", marginBottom: 16 },
  h1: { fontSize: 14, fontFamily: "Helvetica-Bold", marginTop: 14, marginBottom: 6 },
  h2: { fontSize: 12, fontFamily: "Helvetica-Bold", marginTop: 10, marginBottom: 4 },
  bold: { fontFamily: "Helvetica-Bold" },
  paragraph: { marginBottom: 6 },
  bullet: { flexDirection: "row", marginBottom: 3, paddingLeft: 8 },
  bulletDot: { width: 12 },
  sourcesTitle: { fontSize: 11, fontFamily: "Helvetica-Bold", marginTop: 18, marginBottom: 6 },
  source: { fontSize: 9, color: "#475569", marginBottom: 3 },
  footer: {
    position: "absolute",
    bottom: 20,
    left: 40,
    right: 40,
    fontSize: 8,
    color: "#94a3b8",
    textAlign: "center",
  },
});

/** Renders **bold** spans within a single line of text. */
function InlineText({ line }: { line: string }) {
  const parts = line.split(/(\*\*[^*]+\*\*)/g).filter(Boolean);
  return (
    <Text>
      {parts.map((part, i) =>
        part.startsWith("**") && part.endsWith("**") ? (
          <Text key={i} style={styles.bold}>
            {part.slice(2, -2)}
          </Text>
        ) : (
          <Text key={i}>{part}</Text>
        )
      )}
    </Text>
  );
}

/** Minimal markdown-ish renderer: headings (#, ##), bullets (-, *), and paragraphs. */
function ContentBody({ text }: { text: string }) {
  const lines = text.split("\n");
  return (
    <>
      {lines.map((raw, i) => {
        const line = raw.trim();
        if (!line) return null;
        if (line.startsWith("## ")) return <Text key={i} style={styles.h2}>{line.slice(3)}</Text>;
        if (line.startsWith("# ")) return <Text key={i} style={styles.h1}>{line.slice(2)}</Text>;
        if (line.startsWith("- ") || line.startsWith("* ")) {
          return (
            <View key={i} style={styles.bullet}>
              <Text style={styles.bulletDot}>{"•"}</Text>
              <InlineText line={line.slice(2)} />
            </View>
          );
        }
        return (
          <View key={i} style={styles.paragraph}>
            <InlineText line={line} />
          </View>
        );
      })}
    </>
  );
}

const TASK_LABELS: Record<GenerationTaskType, string> = {
  solution: "Step-by-Step Solution",
  notes: "Revision Notes",
  sample_paper: "Sample Paper",
  ad_hoc: "Answer",
};

export interface RenderPdfInput {
  taskType: GenerationTaskType;
  title: string;
  studentName: string;
  content: string;
  sources: MatchedChunk[];
}

export async function renderGenerationPdf(input: RenderPdfInput): Promise<Buffer> {
  const doc = (
    <Document>
      <Page size="A4" style={styles.page}>
        <Text style={styles.title}>{input.title}</Text>
        <Text style={styles.subtitle}>
          {TASK_LABELS[input.taskType]} · Generated for {input.studentName} · StudySprint
        </Text>

        <ContentBody text={input.content} />

        {input.sources.length > 0 && (
          <>
            <Text style={styles.sourcesTitle}>Sources</Text>
            {input.sources.map((s, i) => (
              <Text key={s.id} style={styles.source}>
                [{i + 1}] {s.section_label ?? s.source_type}
                {s.page_number ? `, p.${s.page_number}` : ""}
              </Text>
            ))}
          </>
        )}

        <Text style={styles.footer} fixed>
          Generated by StudySprint — for personal study use.
        </Text>
      </Page>
    </Document>
  );

  return renderToBuffer(doc);
}
